### ISSUE TITLE
ability to decode Trident raw read data

### ISSUE THREAD

**Issue by louking** [louking/tm-csv-connector#75]
Looking to decode read data from Trident, possibly using two modes: upload and live.

- [ ] ~~For live, maybe have connection from the Results view, and separate display~~ (moved to #77)
- [x] For upload, allow upload to add data for the display.
  - [x] after drag into Import File, show filename
  - [ ] ~~resolve gateway timeout 504 on large file import~~ (moved to #76)
- [x] chip to bib table
- [x] Filter on chip number or bib number
- [x] Spinner when server retrieval
- [ ] ~~Chips nav should be no-op~~ (moved to #78)
- [x] ~~redraw table periodically [maybe this isn't necessary or desired]~~

Do we need bib to participant data?
